<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="styles/style.css">
    <title>W.O.R.K_Shop</title>
    <link rel="icon" href="favicon.ico" type="image/x-icon">
</head>
<header>
    <img src="styles/images/logo.png" alt="Logo" class="header-logo">
    <div> W.O.R.K_Shop </div>
    <nav>
        <ul>
            <li><a href="index.php">Home</a></li>
            <li><a href="about.php">About</a></li>
            <li><a href="contact.php">Contact</a></li>
        </ul>
    </nav>
</header>